// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger Hello Example
//
//  This is a sample server hello server.
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/problem+json
//
// swagger:meta
package restapi
