// Code generated by go-swagger; DO NOT EDIT.

package example

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ma91n/rfc7807gen/models"
)

// HelloOKCode is the HTTP code returned for type HelloOK
const HelloOKCode int = 200

/*HelloOK successful operation

swagger:response helloOK
*/
type HelloOK struct {

	/*
	  In: Body
	*/
	Payload *models.Hello `json:"body,omitempty"`
}

// NewHelloOK creates HelloOK with default headers values
func NewHelloOK() *HelloOK {

	return &HelloOK{}
}

// WithPayload adds the payload to the hello o k response
func (o *HelloOK) WithPayload(payload *models.Hello) *HelloOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the hello o k response
func (o *HelloOK) SetPayload(payload *models.Hello) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HelloOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
